### ISSUE TITLE
simnet model in ppo_policy_training notebook

### ISSUE THREAD

**Issue by jayabrata97** [woven-planet/l5kit#375]
1. Is simnet model incorporated in the ppo_policy_training.ipynb notebook now? I can see SimNet model only in ppo_training.py.
2. When I am trying to run ppo_training.py, I am getting error. TypeError: __init__() got an unexpected keyword argument 'simnet_model_path'.
Can anyone help me out in these issues?

**Comment by perone** [comment]
Hey @jayabrata97, did you try to use the `examples/RL/ppo_training.py` example ? There is a way to specify the model there. cc @theDebugger811

**Comment by jayabrata97** [comment]
I tried to run `examples/RL/ppo_training.py` as 'python ppo_training.py --simnet --simnet_model_path='/home/$USER/l5kit/examples/simulation/simulation_model_20210416_5steps.pt'. I am getting error: TypeError: __init__() got an unexpected keyword argument 'simnet_model_path'. Can you please tell me where I am making mistake? Also if possible please show how to run ppo_training.py with simnet model.

**Comment by jayabrata97** [comment]
I think this problem was due to version of l5kit. I installed l5kit with `pip install l5kit`. It installed version 1.5.0. In that version, there was no `simnet_model_path` kwarg in L5Env class in `l5kit/l5kit/environment/envs/l5_env.py`.
