### ISSUE TITLE
zarr dataset path should end with .zarr for `ppo_training.py`

### ISSUE THREAD

**Issue by jayabrata97** [woven-planet/l5kit#376]
HI I am trying to run `examples/RL/ppo_training.py`. I am getting `RuntimeWarning: zarr dataset path should end with .zarr (for now). Open will fail for this dataset!` ` new_dataset = ChunkedDataset("")`. Can anyone tell my mistake? @theDebugger811 , do you have any idea?

**Comment by jeffreywu13579** [comment]
@jayabrata97 Running into the same RuntimeWarning. How did you manage to fix this? Thanks!

**Comment by jayabrata97** [comment]
I can not fix it. By the way, it is a warning so you can ignore it.
