### ISSUE TITLE
Conner of the download of dataset

### ISSUE THREAD

**Issue by Curtainzsl** [woven-planet/l5kit#416]
When I was instructed to go to the data set download screen, I found that the screen would not open. May I ask what operation is needed to solve this problem? Thank you very much for your help！
![image](https://github.com/woven-planet/l5kit/assets/125982935/a885c908-bb68-46a1-b2e0-ab940dcd56b7)

**Comment by stefanopini** [comment]
Hi, apologies for the disruption. We've moved the content to a new domain and we are still in the process of updating all the links, please find the prediction dataset at https://woven.toyota/en/prediction-dataset
